### PR TITLE
Upgrading to V7

### PR DESCRIPTION
**Pull request by edjuaro**
This is a complete rewrite of HierarchicalClustering. Porting the module to Python 3.6.

This code has been tested on the gp-beta-ami.

Github is saying we "can't automatically merge" but I think this is because the LICENSE.txt was modified after I created the develop branch, hopefully resolving that conflict is not a big deal.

### CODE REVIEW

**Comment by peterjcarr** [comment]
This merge will break the automated build, for example [jenkins:Release_GenePattern_Module, build 389](http://cancerdev/hudson/job/Release_GenePattern_Module/389/).

I edited the version comment in the manifest file, which fixed the problem.

**Comment by peterjcarr** [comment]
Create a new pull request with the fix I just committed to the develop branch.

**Note**: the release failed because of a bug in the ant script. It doesn't have anything to do with the module code. 

The "createRelease" ant target, in genepattern_modules/releaseModule.xml POSTs a JSON object to the GitHub API. The version content from the manifest is included in that object. Unfortunately, the ant script does not handle JSON special-characters such as `"`, `,`,`{`, and `}`. We should fix this soon.

**Comment by peterjcarr** [comment]
Note: I resolved the merge conflicts between master and develop, to address the "can't automatically merge" error message.

**Comment by bahill** [comment]
Accepting on behalf of Peter as well.

**Pull request merged**
